/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport }              from './routes/__root'
import { Route as MentorRouteImport }            from './routes/mentor'
import { Route as SocialIntelligenceRouteImport } from './routes/social-intelligence'
import { Route as TendenciasRouteImport }         from './routes/tendencias'
import { Route as SentimentoRouteImport }         from './routes/sentimento'
import { Route as CanaisRouteImport }             from './routes/canais'
import { Route as PrecificacaoRouteImport }       from './routes/precificacao'
import { Route as DnaRouteImport }                from './routes/dna'
import { Route as InovacaoRouteImport }           from './routes/inovacao'
import { Route as ComplianceRouteImport }         from './routes/compliance'
import { Route as ConcorrentesRouteImport }       from './routes/concorrentes'
import { Route as AudienciaRouteImport }          from './routes/audiencia'
import { Route as InvestimentoRouteImport }       from './routes/investimento'
import { Route as BusinessPlanRouteImport }       from './routes/business-plan'
import { Route as DoresRouteImport }              from './routes/dores'
import { Route as VereditorRouteImport }          from './routes/veredito'
import { Route as MercadoRouteImport }            from './routes/mercado'
import { Route as PulsoRouteImport }              from './routes/pulso'
import { Route as BenchmarkingRouteImport }       from './routes/benchmarking'
import { Route as StakeholdersRouteImport }       from './routes/stakeholders'
import { Route as AudienciaHubRouteImport }       from './routes/audiencia-hub'
import { Route as MarcaHubRouteImport }           from './routes/marca-hub'
import { Route as EstrategiaHubRouteImport }      from './routes/estrategia-hub'
import { Route as ScoreFinalRouteImport }         from './routes/score-final'
import { Route as CenariosRouteImport }           from './routes/cenarios'
import { Route as OKRRouteImport }                from './routes/okr'
import { Route as ComparativoRouteImport }        from './routes/comparativo'
import { Route as ExportacaoRouteImport }         from './routes/exportacao'
import { Route as HistoricoRouteImport }          from './routes/historico'
import { Route as RelatorioRouteImport }          from './routes/relatorio'
import { Route as IndexRouteImport }              from './routes/index'

const MentorRoute              = MentorRouteImport.update({              id: '/mentor',              path: '/mentor',              getParentRoute: () => rootRouteImport } as any)
const SocialIntelligenceRoute  = SocialIntelligenceRouteImport.update({  id: '/social-intelligence', path: '/social-intelligence', getParentRoute: () => rootRouteImport } as any)
const TendenciasRoute          = TendenciasRouteImport.update({          id: '/tendencias',          path: '/tendencias',          getParentRoute: () => rootRouteImport } as any)
const SentimentoRoute          = SentimentoRouteImport.update({          id: '/sentimento',          path: '/sentimento',          getParentRoute: () => rootRouteImport } as any)
const CanaisRoute              = CanaisRouteImport.update({              id: '/canais',              path: '/canais',              getParentRoute: () => rootRouteImport } as any)
const PrecificacaoRoute        = PrecificacaoRouteImport.update({        id: '/precificacao',        path: '/precificacao',        getParentRoute: () => rootRouteImport } as any)
const DnaRoute                 = DnaRouteImport.update({                 id: '/dna',                 path: '/dna',                 getParentRoute: () => rootRouteImport } as any)
const InovacaoRoute            = InovacaoRouteImport.update({            id: '/inovacao',            path: '/inovacao',            getParentRoute: () => rootRouteImport } as any)
const ComplianceRoute          = ComplianceRouteImport.update({          id: '/compliance',          path: '/compliance',          getParentRoute: () => rootRouteImport } as any)
const ConcorrentesRoute        = ConcorrentesRouteImport.update({        id: '/concorrentes',        path: '/concorrentes',        getParentRoute: () => rootRouteImport } as any)
const AudienciaRoute           = AudienciaRouteImport.update({           id: '/audiencia',           path: '/audiencia',           getParentRoute: () => rootRouteImport } as any)
const InvestimentoRoute        = InvestimentoRouteImport.update({        id: '/investimento',        path: '/investimento',        getParentRoute: () => rootRouteImport } as any)
const BusinessPlanRoute        = BusinessPlanRouteImport.update({        id: '/business-plan',       path: '/business-plan',       getParentRoute: () => rootRouteImport } as any)
const DoresRoute               = DoresRouteImport.update({               id: '/dores',               path: '/dores',               getParentRoute: () => rootRouteImport } as any)
const VereditorRoute           = VereditorRouteImport.update({           id: '/veredito',            path: '/veredito',            getParentRoute: () => rootRouteImport } as any)
const MercadoRoute             = MercadoRouteImport.update({             id: '/mercado',             path: '/mercado',             getParentRoute: () => rootRouteImport } as any)
const PulsoRoute               = PulsoRouteImport.update({               id: '/pulso',               path: '/pulso',               getParentRoute: () => rootRouteImport } as any)
const BenchmarkingRoute        = BenchmarkingRouteImport.update({        id: '/benchmarking',        path: '/benchmarking',        getParentRoute: () => rootRouteImport } as any)
const StakeholdersRoute        = StakeholdersRouteImport.update({        id: '/stakeholders',        path: '/stakeholders',        getParentRoute: () => rootRouteImport } as any)
const AudienciaHubRoute        = AudienciaHubRouteImport.update({        id: '/audiencia-hub',       path: '/audiencia-hub',       getParentRoute: () => rootRouteImport } as any)
const MarcaHubRoute            = MarcaHubRouteImport.update({            id: '/marca-hub',           path: '/marca-hub',           getParentRoute: () => rootRouteImport } as any)
const EstrategiaHubRoute       = EstrategiaHubRouteImport.update({       id: '/estrategia-hub',      path: '/estrategia-hub',      getParentRoute: () => rootRouteImport } as any)
const ScoreFinalRoute          = ScoreFinalRouteImport.update({          id: '/score-final',         path: '/score-final',         getParentRoute: () => rootRouteImport } as any)
const CenariosRoute            = CenariosRouteImport.update({            id: '/cenarios',            path: '/cenarios',            getParentRoute: () => rootRouteImport } as any)
const OKRRoute                 = OKRRouteImport.update({                 id: '/okr',                 path: '/okr',                 getParentRoute: () => rootRouteImport } as any)
const ComparativoRoute         = ComparativoRouteImport.update({         id: '/comparativo',         path: '/comparativo',         getParentRoute: () => rootRouteImport } as any)
const ExportacaoRoute          = ExportacaoRouteImport.update({          id: '/exportacao',          path: '/exportacao',          getParentRoute: () => rootRouteImport } as any)
const HistoricoRoute           = HistoricoRouteImport.update({           id: '/historico',           path: '/historico',           getParentRoute: () => rootRouteImport } as any)
const RelatorioRoute           = RelatorioRouteImport.update({           id: '/relatorio',           path: '/relatorio',           getParentRoute: () => rootRouteImport } as any)
const IndexRoute               = IndexRouteImport.update({               id: '/',                    path: '/',                    getParentRoute: () => rootRouteImport } as any)

export interface FileRoutesByFullPath {
  '/':                    typeof IndexRoute
  '/mentor':              typeof MentorRoute
  '/social-intelligence': typeof SocialIntelligenceRoute
  '/tendencias':          typeof TendenciasRoute
  '/sentimento':          typeof SentimentoRoute
  '/canais':              typeof CanaisRoute
  '/precificacao':        typeof PrecificacaoRoute
  '/dna':                 typeof DnaRoute
  '/inovacao':            typeof InovacaoRoute
  '/compliance':          typeof ComplianceRoute
  '/concorrentes':        typeof ConcorrentesRoute
  '/audiencia':           typeof AudienciaRoute
  '/investimento':        typeof InvestimentoRoute
  '/business-plan':       typeof BusinessPlanRoute
  '/dores':               typeof DoresRoute
  '/veredito':            typeof VereditorRoute
  '/mercado':             typeof MercadoRoute
  '/pulso':               typeof PulsoRoute
  '/benchmarking':        typeof BenchmarkingRoute
  '/stakeholders':        typeof StakeholdersRoute
  '/audiencia-hub':       typeof AudienciaHubRoute
  '/marca-hub':           typeof MarcaHubRoute
  '/estrategia-hub':      typeof EstrategiaHubRoute
  '/score-final':         typeof ScoreFinalRoute
  '/cenarios':            typeof CenariosRoute
  '/okr':                 typeof OKRRoute
  '/comparativo':         typeof ComparativoRoute
  '/exportacao':          typeof ExportacaoRoute
  '/historico':           typeof HistoricoRoute
  '/relatorio':           typeof RelatorioRoute
}
export interface FileRoutesByTo {
  '/':                    typeof IndexRoute
  '/mentor':              typeof MentorRoute
  '/social-intelligence': typeof SocialIntelligenceRoute
  '/tendencias':          typeof TendenciasRoute
  '/sentimento':          typeof SentimentoRoute
  '/canais':              typeof CanaisRoute
  '/precificacao':        typeof PrecificacaoRoute
  '/dna':                 typeof DnaRoute
  '/inovacao':            typeof InovacaoRoute
  '/compliance':          typeof ComplianceRoute
  '/concorrentes':        typeof ConcorrentesRoute
  '/audiencia':           typeof AudienciaRoute
  '/investimento':        typeof InvestimentoRoute
  '/business-plan':       typeof BusinessPlanRoute
  '/dores':               typeof DoresRoute
  '/veredito':            typeof VereditorRoute
  '/mercado':             typeof MercadoRoute
  '/pulso':               typeof PulsoRoute
  '/benchmarking':        typeof BenchmarkingRoute
  '/stakeholders':        typeof StakeholdersRoute
  '/audiencia-hub':       typeof AudienciaHubRoute
  '/marca-hub':           typeof MarcaHubRoute
  '/estrategia-hub':      typeof EstrategiaHubRoute
  '/score-final':         typeof ScoreFinalRoute
  '/cenarios':            typeof CenariosRoute
  '/okr':                 typeof OKRRoute
  '/comparativo':         typeof ComparativoRoute
  '/exportacao':          typeof ExportacaoRoute
  '/historico':           typeof HistoricoRoute
  '/relatorio':           typeof RelatorioRoute
}
export interface FileRoutesById {
  __root__:               typeof rootRouteImport
  '/':                    typeof IndexRoute
  '/mentor':              typeof MentorRoute
  '/social-intelligence': typeof SocialIntelligenceRoute
  '/tendencias':          typeof TendenciasRoute
  '/sentimento':          typeof SentimentoRoute
  '/canais':              typeof CanaisRoute
  '/precificacao':        typeof PrecificacaoRoute
  '/dna':                 typeof DnaRoute
  '/inovacao':            typeof InovacaoRoute
  '/compliance':          typeof ComplianceRoute
  '/concorrentes':        typeof ConcorrentesRoute
  '/audiencia':           typeof AudienciaRoute
  '/investimento':        typeof InvestimentoRoute
  '/business-plan':       typeof BusinessPlanRoute
  '/dores':               typeof DoresRoute
  '/veredito':            typeof VereditorRoute
  '/mercado':             typeof MercadoRoute
  '/pulso':               typeof PulsoRoute
  '/benchmarking':        typeof BenchmarkingRoute
  '/stakeholders':        typeof StakeholdersRoute
  '/audiencia-hub':       typeof AudienciaHubRoute
  '/marca-hub':           typeof MarcaHubRoute
  '/estrategia-hub':      typeof EstrategiaHubRoute
  '/score-final':         typeof ScoreFinalRoute
  '/cenarios':            typeof CenariosRoute
  '/okr':                 typeof OKRRoute
  '/comparativo':         typeof ComparativoRoute
  '/exportacao':          typeof ExportacaoRoute
  '/historico':           typeof HistoricoRoute
  '/relatorio':           typeof RelatorioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/' | '/mentor' | '/social-intelligence' | '/tendencias' | '/sentimento'
    | '/canais' | '/precificacao' | '/dna' | '/inovacao' | '/compliance'
    | '/concorrentes' | '/audiencia' | '/investimento' | '/business-plan' | '/dores'
    | '/veredito' | '/mercado' | '/pulso' | '/benchmarking' | '/stakeholders'
    | '/audiencia-hub' | '/marca-hub' | '/estrategia-hub' | '/score-final'
    | '/cenarios' | '/okr' | '/comparativo' | '/exportacao' | '/historico' | '/relatorio'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/' | '/mentor' | '/social-intelligence' | '/tendencias' | '/sentimento'
    | '/canais' | '/precificacao' | '/dna' | '/inovacao' | '/compliance'
    | '/concorrentes' | '/audiencia' | '/investimento' | '/business-plan' | '/dores'
    | '/veredito' | '/mercado' | '/pulso' | '/benchmarking' | '/stakeholders'
    | '/audiencia-hub' | '/marca-hub' | '/estrategia-hub' | '/score-final'
    | '/cenarios' | '/okr' | '/comparativo' | '/exportacao' | '/historico' | '/relatorio'
  id:
    | '__root__' | '/' | '/mentor' | '/social-intelligence' | '/tendencias' | '/sentimento'
    | '/canais' | '/precificacao' | '/dna' | '/inovacao' | '/compliance'
    | '/concorrentes' | '/audiencia' | '/investimento' | '/business-plan' | '/dores'
    | '/veredito' | '/mercado' | '/pulso' | '/benchmarking' | '/stakeholders'
    | '/audiencia-hub' | '/marca-hub' | '/estrategia-hub' | '/score-final'
    | '/cenarios' | '/okr' | '/comparativo' | '/exportacao' | '/historico' | '/relatorio'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute:              typeof IndexRoute
  MentorRoute:             typeof MentorRoute
  SocialIntelligenceRoute: typeof SocialIntelligenceRoute
  TendenciasRoute:         typeof TendenciasRoute
  SentimentoRoute:         typeof SentimentoRoute
  CanaisRoute:             typeof CanaisRoute
  PrecificacaoRoute:       typeof PrecificacaoRoute
  DnaRoute:                typeof DnaRoute
  InovacaoRoute:           typeof InovacaoRoute
  ComplianceRoute:         typeof ComplianceRoute
  ConcorrentesRoute:       typeof ConcorrentesRoute
  AudienciaRoute:          typeof AudienciaRoute
  InvestimentoRoute:       typeof InvestimentoRoute
  BusinessPlanRoute:       typeof BusinessPlanRoute
  DoresRoute:              typeof DoresRoute
  VereditorRoute:          typeof VereditorRoute
  MercadoRoute:            typeof MercadoRoute
  PulsoRoute:              typeof PulsoRoute
  BenchmarkingRoute:       typeof BenchmarkingRoute
  StakeholdersRoute:       typeof StakeholdersRoute
  AudienciaHubRoute:       typeof AudienciaHubRoute
  MarcaHubRoute:           typeof MarcaHubRoute
  EstrategiaHubRoute:      typeof EstrategiaHubRoute
  ScoreFinalRoute:         typeof ScoreFinalRoute
  CenariosRoute:           typeof CenariosRoute
  OKRRoute:                typeof OKRRoute
  ComparativoRoute:        typeof ComparativoRoute
  ExportacaoRoute:         typeof ExportacaoRoute
  HistoricoRoute:          typeof HistoricoRoute
  RelatorioRoute:          typeof RelatorioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mentor':              { id: '/mentor';              path: '/mentor';              fullPath: '/mentor';              preLoaderRoute: typeof MentorRouteImport;             parentRoute: typeof rootRouteImport }
    '/social-intelligence': { id: '/social-intelligence'; path: '/social-intelligence'; fullPath: '/social-intelligence'; preLoaderRoute: typeof SocialIntelligenceRouteImport;  parentRoute: typeof rootRouteImport }
    '/tendencias':          { id: '/tendencias';          path: '/tendencias';          fullPath: '/tendencias';          preLoaderRoute: typeof TendenciasRouteImport;          parentRoute: typeof rootRouteImport }
    '/sentimento':          { id: '/sentimento';          path: '/sentimento';          fullPath: '/sentimento';          preLoaderRoute: typeof SentimentoRouteImport;          parentRoute: typeof rootRouteImport }
    '/canais':              { id: '/canais';              path: '/canais';              fullPath: '/canais';              preLoaderRoute: typeof CanaisRouteImport;              parentRoute: typeof rootRouteImport }
    '/precificacao':        { id: '/precificacao';        path: '/precificacao';        fullPath: '/precificacao';        preLoaderRoute: typeof PrecificacaoRouteImport;        parentRoute: typeof rootRouteImport }
    '/dna':                 { id: '/dna';                 path: '/dna';                 fullPath: '/dna';                 preLoaderRoute: typeof DnaRouteImport;                 parentRoute: typeof rootRouteImport }
    '/inovacao':            { id: '/inovacao';            path: '/inovacao';            fullPath: '/inovacao';            preLoaderRoute: typeof InovacaoRouteImport;            parentRoute: typeof rootRouteImport }
    '/compliance':          { id: '/compliance';          path: '/compliance';          fullPath: '/compliance';          preLoaderRoute: typeof ComplianceRouteImport;          parentRoute: typeof rootRouteImport }
    '/concorrentes':        { id: '/concorrentes';        path: '/concorrentes';        fullPath: '/concorrentes';        preLoaderRoute: typeof ConcorrentesRouteImport;        parentRoute: typeof rootRouteImport }
    '/audiencia':           { id: '/audiencia';           path: '/audiencia';           fullPath: '/audiencia';           preLoaderRoute: typeof AudienciaRouteImport;           parentRoute: typeof rootRouteImport }
    '/investimento':        { id: '/investimento';        path: '/investimento';        fullPath: '/investimento';        preLoaderRoute: typeof InvestimentoRouteImport;        parentRoute: typeof rootRouteImport }
    '/business-plan':       { id: '/business-plan';       path: '/business-plan';       fullPath: '/business-plan';       preLoaderRoute: typeof BusinessPlanRouteImport;        parentRoute: typeof rootRouteImport }
    '/dores':               { id: '/dores';               path: '/dores';               fullPath: '/dores';               preLoaderRoute: typeof DoresRouteImport;               parentRoute: typeof rootRouteImport }
    '/':                    { id: '/';                    path: '/';                    fullPath: '/';                    preLoaderRoute: typeof IndexRouteImport;               parentRoute: typeof rootRouteImport }
    '/veredito':            { id: '/veredito';            path: '/veredito';            fullPath: '/veredito';            preLoaderRoute: typeof VereditorRouteImport;           parentRoute: typeof rootRouteImport }
    '/mercado':             { id: '/mercado';             path: '/mercado';             fullPath: '/mercado';             preLoaderRoute: typeof MercadoRouteImport;             parentRoute: typeof rootRouteImport }
    '/pulso':               { id: '/pulso';               path: '/pulso';               fullPath: '/pulso';               preLoaderRoute: typeof PulsoRouteImport;               parentRoute: typeof rootRouteImport }
    '/benchmarking':        { id: '/benchmarking';        path: '/benchmarking';        fullPath: '/benchmarking';        preLoaderRoute: typeof BenchmarkingRouteImport;        parentRoute: typeof rootRouteImport }
    '/stakeholders':        { id: '/stakeholders';        path: '/stakeholders';        fullPath: '/stakeholders';        preLoaderRoute: typeof StakeholdersRouteImport;        parentRoute: typeof rootRouteImport }
    '/audiencia-hub':       { id: '/audiencia-hub';       path: '/audiencia-hub';       fullPath: '/audiencia-hub';       preLoaderRoute: typeof AudienciaHubRouteImport;        parentRoute: typeof rootRouteImport }
    '/marca-hub':           { id: '/marca-hub';           path: '/marca-hub';           fullPath: '/marca-hub';           preLoaderRoute: typeof MarcaHubRouteImport;            parentRoute: typeof rootRouteImport }
    '/estrategia-hub':      { id: '/estrategia-hub';      path: '/estrategia-hub';      fullPath: '/estrategia-hub';      preLoaderRoute: typeof EstrategiaHubRouteImport;       parentRoute: typeof rootRouteImport }
    '/score-final':         { id: '/score-final';         path: '/score-final';         fullPath: '/score-final';         preLoaderRoute: typeof ScoreFinalRouteImport;          parentRoute: typeof rootRouteImport }
    '/cenarios':            { id: '/cenarios';            path: '/cenarios';            fullPath: '/cenarios';            preLoaderRoute: typeof CenariosRouteImport;            parentRoute: typeof rootRouteImport }
    '/okr':                 { id: '/okr';                 path: '/okr';                 fullPath: '/okr';                 preLoaderRoute: typeof OKRRouteImport;                 parentRoute: typeof rootRouteImport }
    '/comparativo':         { id: '/comparativo';         path: '/comparativo';         fullPath: '/comparativo';         preLoaderRoute: typeof ComparativoRouteImport;         parentRoute: typeof rootRouteImport }
    '/exportacao':          { id: '/exportacao';          path: '/exportacao';          fullPath: '/exportacao';          preLoaderRoute: typeof ExportacaoRouteImport;          parentRoute: typeof rootRouteImport }
    '/historico':           { id: '/historico';           path: '/historico';           fullPath: '/historico';           preLoaderRoute: typeof HistoricoRouteImport;           parentRoute: typeof rootRouteImport }
    '/relatorio':           { id: '/relatorio';           path: '/relatorio';           fullPath: '/relatorio';           preLoaderRoute: typeof RelatorioRouteImport;           parentRoute: typeof rootRouteImport }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute, MentorRoute, SocialIntelligenceRoute, TendenciasRoute, SentimentoRoute,
  CanaisRoute, PrecificacaoRoute, DnaRoute, InovacaoRoute, ComplianceRoute,
  ConcorrentesRoute, AudienciaRoute, InvestimentoRoute, BusinessPlanRoute, DoresRoute,
  VereditorRoute, MercadoRoute, PulsoRoute, BenchmarkingRoute, StakeholdersRoute,
  AudienciaHubRoute, MarcaHubRoute, EstrategiaHubRoute, ScoreFinalRoute,
  CenariosRoute, OKRRoute, ComparativoRoute, ExportacaoRoute, HistoricoRoute,
  RelatorioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register { ssr: true; router: Awaited<ReturnType<typeof getRouter>> }
}
