/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SocialIntelligenceRouteImport } from './routes/social-intelligence'
import { Route as InvestimentoRouteImport } from './routes/investimento'
import { Route as ConcorrentesRouteImport } from './routes/concorrentes'
import { Route as BusinessPlanRouteImport } from './routes/business-plan'
import { Route as AudienciaRouteImport } from './routes/audiencia'
import { Route as IndexRouteImport } from './routes/index'

const SocialIntelligenceRoute = SocialIntelligenceRouteImport.update({
  id: '/social-intelligence',
  path: '/social-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestimentoRoute = InvestimentoRouteImport.update({
  id: '/investimento',
  path: '/investimento',
  getParentRoute: () => rootRouteImport,
} as any)
const ConcorrentesRoute = ConcorrentesRouteImport.update({
  id: '/concorrentes',
  path: '/concorrentes',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessPlanRoute = BusinessPlanRouteImport.update({
  id: '/business-plan',
  path: '/business-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const AudienciaRoute = AudienciaRouteImport.update({
  id: '/audiencia',
  path: '/audiencia',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audiencia': typeof AudienciaRoute
  '/business-plan': typeof BusinessPlanRoute
  '/concorrentes': typeof ConcorrentesRoute
  '/investimento': typeof InvestimentoRoute
  '/social-intelligence': typeof SocialIntelligenceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audiencia': typeof AudienciaRoute
  '/business-plan': typeof BusinessPlanRoute
  '/concorrentes': typeof ConcorrentesRoute
  '/investimento': typeof InvestimentoRoute
  '/social-intelligence': typeof SocialIntelligenceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audiencia': typeof AudienciaRoute
  '/business-plan': typeof BusinessPlanRoute
  '/concorrentes': typeof ConcorrentesRoute
  '/investimento': typeof InvestimentoRoute
  '/social-intelligence': typeof SocialIntelligenceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audiencia'
    | '/business-plan'
    | '/concorrentes'
    | '/investimento'
    | '/social-intelligence'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audiencia'
    | '/business-plan'
    | '/concorrentes'
    | '/investimento'
    | '/social-intelligence'
  id:
    | '__root__'
    | '/'
    | '/audiencia'
    | '/business-plan'
    | '/concorrentes'
    | '/investimento'
    | '/social-intelligence'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AudienciaRoute: typeof AudienciaRoute
  BusinessPlanRoute: typeof BusinessPlanRoute
  ConcorrentesRoute: typeof ConcorrentesRoute
  InvestimentoRoute: typeof InvestimentoRoute
  SocialIntelligenceRoute: typeof SocialIntelligenceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/social-intelligence': {
      id: '/social-intelligence'
      path: '/social-intelligence'
      fullPath: '/social-intelligence'
      preLoaderRoute: typeof SocialIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investimento': {
      id: '/investimento'
      path: '/investimento'
      fullPath: '/investimento'
      preLoaderRoute: typeof InvestimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concorrentes': {
      id: '/concorrentes'
      path: '/concorrentes'
      fullPath: '/concorrentes'
      preLoaderRoute: typeof ConcorrentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-plan': {
      id: '/business-plan'
      path: '/business-plan'
      fullPath: '/business-plan'
      preLoaderRoute: typeof BusinessPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audiencia': {
      id: '/audiencia'
      path: '/audiencia'
      fullPath: '/audiencia'
      preLoaderRoute: typeof AudienciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AudienciaRoute: AudienciaRoute,
  BusinessPlanRoute: BusinessPlanRoute,
  ConcorrentesRoute: ConcorrentesRoute,
  InvestimentoRoute: InvestimentoRoute,
  SocialIntelligenceRoute: SocialIntelligenceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
