/* eslint-disable */ 

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SocialIntelligenceRouteImport } from './routes/social-intelligence'
import { Route as ConcorrentesRouteImport } from './routes/concorrentes'
import { Route as AudienciaRouteImport } from './routes/audiencia'
import { Route as InvestimentoRouteImport } from './routes/investimento'
import { Route as BusinessPlanRouteImport } from './routes/business-plan'
import { Route as IndexRouteImport } from './routes/index'

const SocialIntelligenceRoute = SocialIntelligenceRouteImport.update({
  id: '/social-intelligence',
  path: '/social-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const ConcorrentesRoute = ConcorrentesRouteImport.update({
  id: '/concorrentes',
  path: '/concorrentes',
  getParentRoute: () => rootRouteImport,
} as any)
const AudienciaRoute = AudienciaRouteImport.update({
  id: '/audiencia',
  path: '/audiencia',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestimentoRoute = InvestimentoRouteImport.update({
  id: '/investimento',
  path: '/investimento',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessPlanRoute = BusinessPlanRouteImport.update({
  id: '/business-plan',
  path: '/business-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/social-intelligence': typeof SocialIntelligenceRoute
  '/concorrentes': typeof ConcorrentesRoute
  '/audiencia': typeof AudienciaRoute
  '/investimento': typeof InvestimentoRoute
  '/business-plan': typeof BusinessPlanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/social-intelligence': typeof SocialIntelligenceRoute
  '/concorrentes': typeof ConcorrentesRoute
  '/audiencia': typeof AudienciaRoute
  '/investimento': typeof InvestimentoRoute
  '/business-plan': typeof BusinessPlanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/social-intelligence': typeof SocialIntelligenceRoute
  '/concorrentes': typeof ConcorrentesRoute
  '/audiencia': typeof AudienciaRoute
  '/investimento': typeof InvestimentoRoute
  '/business-plan': typeof BusinessPlanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/social-intelligence' | '/concorrentes' | '/audiencia' | '/investimento' | '/business-plan'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/social-intelligence' | '/concorrentes' | '/audiencia' | '/investimento' | '/business-plan'
  id: '__root__' | '/' | '/social-intelligence' | '/concorrentes' | '/audiencia' | '/investimento' | '/business-plan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SocialIntelligenceRoute: typeof SocialIntelligenceRoute
  ConcorrentesRoute: typeof ConcorrentesRoute
  AudienciaRoute: typeof AudienciaRoute
  InvestimentoRoute: typeof InvestimentoRoute
  BusinessPlanRoute: typeof BusinessPlanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/social-intelligence': {
      id: '/social-intelligence'
      path: '/social-intelligence'
      fullPath: '/social-intelligence'
      preLoaderRoute: typeof SocialIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concorrentes': {
      id: '/concorrentes'
      path: '/concorrentes'
      fullPath: '/concorrentes'
      preLoaderRoute: typeof ConcorrentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audiencia': {
      id: '/audiencia'
      path: '/audiencia'
      fullPath: '/audiencia'
      preLoaderRoute: typeof AudienciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investimento': {
      id: '/investimento'
      path: '/investimento'
      fullPath: '/investimento'
      preLoaderRoute: typeof InvestimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-plan': {
      id: '/business-plan'
      path: '/business-plan'
      fullPath: '/business-plan'
      preLoaderRoute: typeof BusinessPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SocialIntelligenceRoute: SocialIntelligenceRoute,
  ConcorrentesRoute: ConcorrentesRoute,
  AudienciaRoute: AudienciaRoute,
  InvestimentoRoute: InvestimentoRoute,
  BusinessPlanRoute: BusinessPlanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
